// 1655943580000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "struct_arrays_stub.h"

#define NULL ((void*)0)

int index_of_needed_struct_symbolic[10];
int _index_of_needed_struct_symbolic[10];
int index_of_needed_struct(struct CharAndInt * arr) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_index_of_needed_struct_symbolic, sizeof(_index_of_needed_struct_symbolic), "_index_of_needed_struct_symbolic");
            for (int it_100_0 = 0; it_100_0 < 10; it_100_0 ++) {
                klee_prefer_cex(_index_of_needed_struct_symbolic, _index_of_needed_struct_symbolic[it_100_0] >= -10  & _index_of_needed_struct_symbolic[it_100_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _index_of_needed_struct_symbolic[cntCall++];
}


int index_of_struct_with_equal_fields_symbolic[10];
int _index_of_struct_with_equal_fields_symbolic[10];
int index_of_struct_with_equal_fields(struct Trio * arr) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&_index_of_struct_with_equal_fields_symbolic, sizeof(_index_of_struct_with_equal_fields_symbolic), "_index_of_struct_with_equal_fields_symbolic");
            for (int it_101_0 = 0; it_101_0 < 10; it_101_0 ++) {
                klee_prefer_cex(_index_of_struct_with_equal_fields_symbolic, _index_of_struct_with_equal_fields_symbolic[it_101_0] >= -10  & _index_of_struct_with_equal_fields_symbolic[it_101_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return _index_of_struct_with_equal_fields_symbolic[cntCall++];
}


