/*
 * This file is automatically generated by UnitTestBot. For further information seehttps://unittestbot.org
 */

#include "linked-list_dot_c_test.h"

#include "gtest/gtest.h"
namespace UTBot {
static const float utbot_abs_error = 1e-6;


#pragma region regression
TEST(regression, length_of_linked_list2_test_1)
{
    struct Node head = {
        .x = 0,
        .next = NULL};
    int actual = length_of_linked_list2(&head);
    EXPECT_EQ(1, actual);
    struct Node expected_head = {
        .x = 0,
        .next = NULL};
    EXPECT_EQ(expected_head.x, head.x);
}

TEST(regression, length_of_linked_list2_test_2)
{
    struct Node head = {
        .x = 0,
        .next = NULL};
    struct Node utbotInnerVar1 = {
        .x = 0,
        .next = (struct Node*) 0x0};
    head.next = (struct Node*) &utbotInnerVar1;
    int actual = length_of_linked_list2(&head);
    EXPECT_EQ(-1, actual);
    struct Node expected_head = {
        .x = 0,
        .next = NULL};
    EXPECT_EQ(expected_head.x, head.x);
}

TEST(regression, length_of_linked_list2_test_3)
{
    struct Node head = {
        .x = 0,
        .next = NULL};
    struct Node utbotInnerVar1 = {
        .x = 0,
        .next = NULL};
    head.next = (struct Node*) &utbotInnerVar1;
    int actual = length_of_linked_list2(&head);
    EXPECT_EQ(2, actual);
    struct Node expected_head = {
        .x = 0,
        .next = NULL};
    EXPECT_EQ(expected_head.x, head.x);
}

TEST(regression, length_of_linked_list2_test_4)
{
    struct Node head = {
        .x = 0,
        .next = NULL};
    head.next = (struct Node*) &head;
    int actual = length_of_linked_list2(&head);
    EXPECT_EQ(-2, actual);
    struct Node expected_head = {
        .x = 0,
        .next = NULL};
    EXPECT_EQ(expected_head.x, head.x);
}

#pragma endregion
#pragma region error
TEST(error, length_of_linked_list2_test_5)
{
    struct Node head = {
        .x = 0,
        .next = (struct Node*) 0xffffffff};
    length_of_linked_list2(&head);
}

TEST(error, length_of_linked_list2_test_6)
{
    struct Node head = {
        .x = 0,
        .next = (struct Node*) 0xfffffff8};
    length_of_linked_list2(&head);
}

#pragma endregion
}
